menu:
    - login:
        text: "Přihlásit se"
        icon: "bi-box-arrow-in-right"
        auth: "unauthorized_only"
        handler: "UserAuth.login"
    - logout:
        text: "Odhlásit se"
        icon: "bi-escape"
        auth: "authorized"
        handler: "UserAuth.logout"
    - leaderboard:
        text: "Žebříček překladatelů"
        icon: "bi-trophy"
        auth: "unauthorized"
        handler: "index"
    - leaderboard:
        text: "Statistiky"
        icon: "bi-bar-chart"
        auth: "unauthorized"
        handler: "StatisticsController.view_stats"
    - leaderboard:
        text: "Nové stránky"
        icon: "bi-rss"
        auth: "authorized"
        handler: "RssPageController.rss_changes"
    - backups:
        text: "Zálohy"
        icon: "bi-database"
        auth: "authorized"
        handler: "AutobackupController.backup_index"
    - leaderboard:
        text: "Přidat uživatele"
        icon: "bi-person-add"
        auth: "authorized"
        handler: "UserController.add_user"
    - debug:
        text: "Nástroje pro techniky"
        icon: "bi-braces"
        auth: "authorized"
        handler: "DebugTools.debug_index"